services:
  - type: web
    name: vlinkpay-public-proxy
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: vlinkpay-public-proxy
          property: port